[package]
name = "rusted_list"
version = "0.1.1"
authors = ["Liberatys <Ilithium@protonmail.com>"]
edition = "2019"
description = "A ever sorted list for rust"
readme = "README.md"
keywords = ["list","sorted","hacked"]
license = "MIT/Apache-2.0"

[dependencies]
num = "0.2"
